// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: file_metadata.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName   string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSha256 string `protobuf:"bytes,2,opt,name=file_sha256,json=fileSha256,proto3" json:"file_sha256,omitempty"`
	FileSize   uint64 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	// Types that are assignable to SpecificData:
	//
	//	*FileMetadata_ClientFileInfo
	//	*FileMetadata_ServerFileInfo
	SpecificData isFileMetadata_SpecificData `protobuf_oneof:"SpecificData"`
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_file_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileMetadata) GetFileSha256() string {
	if x != nil {
		return x.FileSha256
	}
	return ""
}

func (x *FileMetadata) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (m *FileMetadata) GetSpecificData() isFileMetadata_SpecificData {
	if m != nil {
		return m.SpecificData
	}
	return nil
}

func (x *FileMetadata) GetClientFileInfo() *ClientFileInfo {
	if x, ok := x.GetSpecificData().(*FileMetadata_ClientFileInfo); ok {
		return x.ClientFileInfo
	}
	return nil
}

func (x *FileMetadata) GetServerFileInfo() *ServerFileInfo {
	if x, ok := x.GetSpecificData().(*FileMetadata_ServerFileInfo); ok {
		return x.ServerFileInfo
	}
	return nil
}

type isFileMetadata_SpecificData interface {
	isFileMetadata_SpecificData()
}

type FileMetadata_ClientFileInfo struct {
	ClientFileInfo *ClientFileInfo `protobuf:"bytes,4,opt,name=client_file_info,json=clientFileInfo,proto3,oneof"`
}

type FileMetadata_ServerFileInfo struct {
	ServerFileInfo *ServerFileInfo `protobuf:"bytes,5,opt,name=server_file_info,json=serverFileInfo,proto3,oneof"`
}

func (*FileMetadata_ClientFileInfo) isFileMetadata_SpecificData() {}

func (*FileMetadata_ServerFileInfo) isFileMetadata_SpecificData() {}

type ClientFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasePath   string `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	FileServer string `protobuf:"bytes,2,opt,name=file_server,json=fileServer,proto3" json:"file_server,omitempty"`
}

func (x *ClientFileInfo) Reset() {
	*x = ClientFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFileInfo) ProtoMessage() {}

func (x *ClientFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFileInfo.ProtoReflect.Descriptor instead.
func (*ClientFileInfo) Descriptor() ([]byte, []int) {
	return file_file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ClientFileInfo) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *ClientFileInfo) GetFileServer() string {
	if x != nil {
		return x.FileServer
	}
	return ""
}

type ServerFileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasePath            string   `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	AuthorizedAccessors []string `protobuf:"bytes,2,rep,name=authorized_accessors,json=authorizedAccessors,proto3" json:"authorized_accessors,omitempty"`
}

func (x *ServerFileInfo) Reset() {
	*x = ServerFileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_metadata_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFileInfo) ProtoMessage() {}

func (x *ServerFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_file_metadata_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFileInfo.ProtoReflect.Descriptor instead.
func (*ServerFileInfo) Descriptor() ([]byte, []int) {
	return file_file_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *ServerFileInfo) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *ServerFileInfo) GetAuthorizedAccessors() []string {
	if x != nil {
		return x.AuthorizedAccessors
	}
	return nil
}

var File_file_metadata_proto protoreflect.FileDescriptor

var file_file_metadata_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x81, 0x02,
	0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x68, 0x61, 0x32, 0x35, 0x36, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x42, 0x0a, 0x10, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x0e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x42, 0x0a,
	0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48,
	0x00, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x42, 0x0e, 0x0a, 0x0c, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x4e, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x22, 0x60, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x50, 0x61, 0x74, 0x68,
	0x12, 0x31, 0x0a, 0x14, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_metadata_proto_rawDescOnce sync.Once
	file_file_metadata_proto_rawDescData = file_file_metadata_proto_rawDesc
)

func file_file_metadata_proto_rawDescGZIP() []byte {
	file_file_metadata_proto_rawDescOnce.Do(func() {
		file_file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_metadata_proto_rawDescData)
	})
	return file_file_metadata_proto_rawDescData
}

var file_file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_file_metadata_proto_goTypes = []interface{}{
	(*FileMetadata)(nil),   // 0: models.FileMetadata
	(*ClientFileInfo)(nil), // 1: models.ClientFileInfo
	(*ServerFileInfo)(nil), // 2: models.ServerFileInfo
}
var file_file_metadata_proto_depIdxs = []int32{
	1, // 0: models.FileMetadata.client_file_info:type_name -> models.ClientFileInfo
	2, // 1: models.FileMetadata.server_file_info:type_name -> models.ServerFileInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_file_metadata_proto_init() }
func file_file_metadata_proto_init() {
	if File_file_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_metadata_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerFileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_file_metadata_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*FileMetadata_ClientFileInfo)(nil),
		(*FileMetadata_ServerFileInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_metadata_proto_goTypes,
		DependencyIndexes: file_file_metadata_proto_depIdxs,
		MessageInfos:      file_file_metadata_proto_msgTypes,
	}.Build()
	File_file_metadata_proto = out.File
	file_file_metadata_proto_rawDesc = nil
	file_file_metadata_proto_goTypes = nil
	file_file_metadata_proto_depIdxs = nil
}
