// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreateNodeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCreateNodeRequest(buf []byte, offset flatbuffers.UOffsetT) *CreateNodeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreateNodeRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCreateNodeRequest(buf []byte, offset flatbuffers.UOffsetT) *CreateNodeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CreateNodeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *CreateNodeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreateNodeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CreateNodeRequest) PrivateKey(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *CreateNodeRequest) PrivateKeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CreateNodeRequest) PrivateKeyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CreateNodeRequest) MutatePrivateKey(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *CreateNodeRequest) UseInternet() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CreateNodeRequest) MutateUseInternet(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func CreateNodeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CreateNodeRequestAddPrivateKey(builder *flatbuffers.Builder, privateKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(privateKey), 0)
}
func CreateNodeRequestStartPrivateKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func CreateNodeRequestAddUseInternet(builder *flatbuffers.Builder, useInternet bool) {
	builder.PrependBoolSlot(1, useInternet, false)
}
func CreateNodeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
