// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DownloadStatusResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDownloadStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *DownloadStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DownloadStatusResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDownloadStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *DownloadStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DownloadStatusResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DownloadStatusResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DownloadStatusResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DownloadStatusResponse) Output(obj *DownloadStatus) *DownloadStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DownloadStatus)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DownloadStatusResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DownloadStatusResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DownloadStatusResponseAddOutput(builder *flatbuffers.Builder, output flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(output), 0)
}
func DownloadStatusResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func DownloadStatusResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
