// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ServeFileRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsServeFileRequest(buf []byte, offset flatbuffers.UOffsetT) *ServeFileRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServeFileRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsServeFileRequest(buf []byte, offset flatbuffers.UOffsetT) *ServeFileRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServeFileRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ServeFileRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServeFileRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ServeFileRequest) FilePath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ServeFileRequest) PeerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ServeFileRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ServeFileRequestAddFilePath(builder *flatbuffers.Builder, filePath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(filePath), 0)
}
func ServeFileRequestAddPeerId(builder *flatbuffers.Builder, peerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(peerId), 0)
}
func ServeFileRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
