// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class GetHelloMessageRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):GetHelloMessageRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetHelloMessageRequest(bb:flatbuffers.ByteBuffer, obj?:GetHelloMessageRequest):GetHelloMessageRequest {
  return (obj || new GetHelloMessageRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetHelloMessageRequest(bb:flatbuffers.ByteBuffer, obj?:GetHelloMessageRequest):GetHelloMessageRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetHelloMessageRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userName():string|null
userName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
userName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startGetHelloMessageRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUserName(builder:flatbuffers.Builder, userNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, userNameOffset, 0);
}

static endGetHelloMessageRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetHelloMessageRequest(builder:flatbuffers.Builder, userNameOffset:flatbuffers.Offset):flatbuffers.Offset {
  GetHelloMessageRequest.startGetHelloMessageRequest(builder);
  GetHelloMessageRequest.addUserName(builder, userNameOffset);
  return GetHelloMessageRequest.endGetHelloMessageRequest(builder);
}
}
