// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class StringRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):StringRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStringRequest(bb:flatbuffers.ByteBuffer, obj?:StringRequest):StringRequest {
  return (obj || new StringRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStringRequest(bb:flatbuffers.ByteBuffer, obj?:StringRequest):StringRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StringRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

input():string|null
input(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
input(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startStringRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addInput(builder:flatbuffers.Builder, inputOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, inputOffset, 0);
}

static endStringRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStringRequest(builder:flatbuffers.Builder, inputOffset:flatbuffers.Offset):flatbuffers.Offset {
  StringRequest.startStringRequest(builder);
  StringRequest.addInput(builder, inputOffset);
  return StringRequest.endStringRequest(builder);
}
}
