name: Build Protocol Buffers

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Overwrite
        required: false
  push:
    paths:
      - '**.fbs'
    tags:
      - "v*"
  pull_request:

env:
  VERSION: ${{ github.event.inputs.version || (startsWith(github.ref, 'refs/tags/') && github.ref || '') }}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        language: [ dart, go ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.7'
      - name: Install Protoc
        run: make protobuf_deps
      - name: Build
        run: make protobuf_${{ matrix.language }}
      - name: Compress
        run: tar -czvf output.tar.gz -C output/protobuf/${{ matrix.language }} .
      - if: ${{ env.VERSION!='' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          asset_name: protobuf_custom_libp2p_bridge_${{ matrix.language }}_$tag.tar.gz
          file: output.tar.gz
          tag: ${{ env.VERSION }}
          overwrite: true
      - if: ${{ env.VERSION=='' }}
        uses: actions/upload-artifact@v3
        with:
          name: protobuf_custom_libp2p_bridge_${{ matrix.language }}
          path: output.tar.gz