name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: heinrichreimer/github-changelog-generator-action@v2.3
        id: changelog
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          onlyLastTag: true
          stripGeneratorNotice: true
          stripHeaders: true
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          allowUpdates: true
          body: |
            ${{ steps.changelog.outputs.changelog }}