name: Tests and Coverage

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.20', '1.19']
    name: Using Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Tests
        run: make test
